# Generated by Django 3.1.2 on 2020-11-02 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('city', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('virustest', models.CharField(max_length=60)),
                ('bloodtype', models.CharField(max_length=60)),
                ('BloodExpirationDate', models.DateField(default=datetime.datetime(2020, 12, 14, 17, 14, 0, 169413))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
