# Generated by Django 3.1.2 on 2020-11-03 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30, null=True)),
                ('patientsStatus', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 11, 25, 52, 172122)),
        ),
    ]
