# Generated by Django 3.1.2 on 2020-11-03 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_auto_20201103_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='bloodQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 16, 21, 43, 333029)),
        ),
    ]
