# Generated by Django 3.1.2 on 2020-11-04 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_auto_20201103_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 0, 11, 24, 899096)),
        ),
    ]
