# Generated by Django 3.1.2 on 2020-11-04 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_auto_20201104_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 0, 13, 14, 188317)),
        ),
    ]
