# Generated by Django 3.1.2 on 2020-11-06 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_auto_20201106_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 19, 28, 38, 448958)),
        ),
    ]
