# Generated by Django 3.1.2 on 2020-11-07 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0009_auto_20201107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='BloodExpirationDate',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 20, 2, 39, 265699)),
        ),
    ]
